import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
    { route: '/about' , name: 'About' }
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
            app name 
            <nav>
                <ul>
                    { links.map( ( link ) => 
                        <li>
                            <Link href={ link.route }> { link.name } </Link>
                        </li>
                    )}
                </ul>
            </nav>
        </header>
        {children}
        </body>
    </html>
  )
}
