import { Inter } from 'next/font/google'
import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'
import UserAuthBar from './auth/userAuthBar';
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
    { route: '/about' , name: 'About' }
];

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
        <body className={inter.className}>
          <header>
              app name 
              <nav>
                  <ul>
                      { links.map( ( link ) => 
                          <li>
                              <Link href={ link.route }> { link.name } </Link>
                          </li>
                      )}
                  </ul>
              </nav>
             <UserAuthBar />
          </header>
          {children}
          </body>
      </html>
    </ClerkProvider>
  )
}
