import { Inter } from 'next/font/google'
import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'

import DashboardLayout from './dashboard/dashboard'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
    { route: '/about' , name: 'About' }
];

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
        <body className={inter.className}>
            <DashboardLayout>
                { children }
            </DashboardLayout>
         </body>
      </html>
    </ClerkProvider>
  )
}
